import type { Metadata } from "next";
import "./styles/app.css";

export const metadata: Metadata = {
  title: "Arena MVP",
  description: "Generated by create next app",
  icons: {
    icon: {
      url: "/assets/favicon.svg",
      type: "image/svg+xml",
    },
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
